# Generated by Django 3.0.6 on 2021-09-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductID', models.IntegerField()),
                ('ProductQuantity', models.IntegerField()),
            ],
        ),
    ]
